title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://elvin.iruthayam.github.io/just-the-doc

aux_links:
  Template Repository: https://github.com/ElvinIruthayam/just-the-docs
